### ISSUE TITLE
Throttle to prevent massive reporting to occur for "infinite" errors

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/logging#6]
In some rare scenarios, page JavaScript can find itself in an infinite (or very large) loop where the same errors get reported over and over again.

This happened recently where the same error was reported from the same user on the same page over 100,000 times in 24 hours. The page must have been constantly throwing and reporting the error more than once per second.

To mitigate against this, we should implement some form of throttling. Some ideas:
* Only report the same error once per instance of the logger, which roughly corresponds to once per page load
* Only report the same error once per "period of time" (e.g. once per minute), reducing the total number of reports for the same error for the same user to ~1440/day.
* Only report the same error "a maximum number of times" (e.g. 100) per instance of the logger

**Comment by dbatiste** [comment]
I think it could be worthwhile to include something to differentiate generic errors like "Uncaught SyntaxError: Invalid or unexpected token", since there are a few of these errors that can have multiple root causes.  On clients sites on a couple of occasions I've seen the same error on the same page for more than one reason.  Not sure how easy that would be, but it would be nice to still log the ones that are seemingly different even though the error message is the same.
